<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <RootNamespace>KitX.Dashboard.Fonts</RootNamespace>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <TrimMode>copyused</TrimMode>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    </PropertyGroup>
    <ItemGroup>
        <None Remove="sarasa-mono-cl-regular.ttf" />
        <None Remove="SourceHanSans-VF.ttf" />
    </ItemGroup>
    <ItemGroup>
        <AvaloniaResource Include="sarasa-mono-cl-regular.ttf" />
        <AvaloniaResource Include="SourceHanSans-VF.ttf" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.3" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    </ItemGroup>
</Project>